-- MySQL Script generated by MySQL Workbench
-- Tue Nov 16 10:08:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lab1db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lab1db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lab1db` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema test11_sash
-- -----------------------------------------------------
-- 
-- 
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mytest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mytest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mytest` DEFAULT CHARACTER SET utf8 ;
USE `lab1db` ;

-- -----------------------------------------------------
-- Table `lab1db`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1db`.`photo` (
  `id_photo` INT NOT NULL AUTO_INCREMENT,
  `photo_name` VARCHAR(45) NULL,
  `date_of_posting` DATETIME NULL,
  PRIMARY KEY (`id_photo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab1db`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1db`.`video` (
  `id_video` INT NOT NULL AUTO_INCREMENT,
  `video_name` VARCHAR(45) NULL,
  `size` INT NULL,
  PRIMARY KEY (`id_video`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab1db`.`insta_story`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1db`.`insta_story` (
  `id_insta_story` INT NOT NULL AUTO_INCREMENT,
  `story_name` VARCHAR(45) NOT NULL,
  `photo_id_photo` INT NULL,
  `video_id_video` INT NULL,
  `date_of_posting` DATE NULL,
  `insta_storycol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_insta_story`),
  INDEX `fk_insta_story_photo1_idx` (`photo_id_photo` ASC) VISIBLE,
  INDEX `fk_insta_story_video1_idx` (`video_id_video` ASC) VISIBLE,
  CONSTRAINT `fk_insta_story_photo1`
    FOREIGN KEY (`photo_id_photo`)
    REFERENCES `lab1db`.`photo` (`id_photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_insta_story_video1`
    FOREIGN KEY (`video_id_video`)
    REFERENCES `lab1db`.`video` (`id_video`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab1db`.`reaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1db`.`reaction` (
  `id_reaction` INT NOT NULL AUTO_INCREMENT,
  `reaction_name` VARCHAR(45) NULL,
  `insta_story_id_insta_story` INT NOT NULL,
  PRIMARY KEY (`id_reaction`),
  INDEX `fk_reaction_insta_story1_idx` (`insta_story_id_insta_story` ASC) VISIBLE,
  CONSTRAINT `fk_reaction_insta_story1`
    FOREIGN KEY (`insta_story_id_insta_story`)
    REFERENCES `lab1db`.`insta_story` (`id_insta_story`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab1db`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1db`.`comment` (
  `id_comment` INT NOT NULL AUTO_INCREMENT,
  `comment_name` VARCHAR(45) NULL,
  `insta_story_id_insta_story` INT NOT NULL,
  PRIMARY KEY (`id_comment`),
  INDEX `fk_comment_insta_story1_idx` (`insta_story_id_insta_story` ASC) VISIBLE,
  CONSTRAINT `fk_comment_insta_story1`
    FOREIGN KEY (`insta_story_id_insta_story`)
    REFERENCES `lab1db`.`insta_story` (`id_insta_story`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab1db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1db`.`user` (
  `id_user` INT NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `user_account_name` VARCHAR(45) NOT NULL,
  `date_of_birth` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NOT NULL,
  `avatar_photo` INT NULL,
  `reaction_id_reaction` INT NOT NULL,
  `comment_id_comment` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_user_photo1_idx` (`avatar_photo` ASC) VISIBLE,
  INDEX `fk_user_reaction1_idx` (`reaction_id_reaction` ASC) VISIBLE,
  INDEX `fk_user_comment1_idx` (`comment_id_comment` ASC) VISIBLE,
  CONSTRAINT `fk_user_photo1`
    FOREIGN KEY (`avatar_photo`)
    REFERENCES `lab1db`.`photo` (`id_photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_reaction1`
    FOREIGN KEY (`reaction_id_reaction`)
    REFERENCES `lab1db`.`reaction` (`id_reaction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_comment1`
    FOREIGN KEY (`comment_id_comment`)
    REFERENCES `lab1db`.`comment` (`id_comment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab1db`.`user_has_insta_story`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1db`.`user_has_insta_story` (
  `insta_story_id_insta_story` INT NOT NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`insta_story_id_insta_story`),
  INDEX `fk_user_has_insta_story_insta_story1_idx` (`insta_story_id_insta_story` ASC) VISIBLE,
  INDEX `fk_user_has_insta_story_user1_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_insta_story_insta_story1`
    FOREIGN KEY (`insta_story_id_insta_story`)
    REFERENCES `lab1db`.`insta_story` (`id_insta_story`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_insta_story_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `lab1db`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab1db`.`security`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1db`.`security` (
  `user_id_user` INT NOT NULL,
  `user_account_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id_user`),
  CONSTRAINT `fk_sec_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `lab1db`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mytest` ;

-- -----------------------------------------------------
-- Table `mytest`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mytest`.`table1` (
  `idstudent` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `table1col` VARCHAR(45) NULL DEFAULT NULL,
  `table1col1` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idstudent`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mytest`.`table2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mytest`.`table2` (
  `idtable2` INT NOT NULL,
  `table2col` DATETIME NULL DEFAULT NULL,
  `table1_idstudent` INT NOT NULL,
  PRIMARY KEY (`idtable2`),
  INDEX `fk_table2_table1_idx` (`table1_idstudent` ASC) VISIBLE,
  CONSTRAINT `fk_table2_table1`
    FOREIGN KEY (`table1_idstudent`)
    REFERENCES `mytest`.`table1` (`idstudent`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
